### ISSUE TITLE
removeClasss uncaught typeerror

### ISSUE THREAD

**Issue by doczoidberg** [kbwood/svg#19]
I use twgantt\* which uses your library.

I am getting the error:
Uncaught TypeError: Cannot use 'in' operator to search for 'marginTop' in undefined

any ideas?

http://roberto.open-lab.com/2012/08/24/jquery-gantt-editor/

**Comment by kbwood** [comment]
Can you provide a page that shows the problem?

**Comment by doczoidberg** [comment]
problem was elsewhere (incorrect use of twgantt templates)
