### ISSUE TITLE
Missing camelCase version of shape-rendering attribute

### ISSUE THREAD

**Issue by kazarmy** [kbwood/svg#21]
Could you please add a camelCase version of [shape-rendering](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/shape-rendering)? When displaying a grid of SVG rectangles, the default value of `shape-rendering` causes unsightly anti-aliasing.

**Comment by kbwood** [comment]
I'll add it in. You can still use it now by enclosing the name in quotes, e.g.

`svg.circle(100, 50, 20, {'shape-rendering': 'optimizeSpeed'});`

**Comment by kazarmy** [comment]
I've added it to `_attrNames` in my local version of `jquery.svg(.min).js`. Do you want a pull request?

**Comment by kbwood** [comment]
No, I've added it locally.
