### ISSUE TITLE
Are jquery.svg.pack.js and jquery.svg.compat-1.0.1.js in the old versions necessary ?

### ISSUE THREAD

**Issue by nolsherry** [kbwood/svg#23]
Hello @kbwood ,
I am the member of [cdnjs](https://github.com/cdnjs/cdnjs) project.
We want to host this library.
Should we also need `jquery.svg.pack.js` and `jquery.svg.compat-1.0.1.js` in the old versions?

cdnjs/cdnjs#9085

**Comment by kbwood** [comment]
No. The pack file is just a minimised version of the basic SVG plugin. The compat file provides backwards compatibility for those with code for the original SVG plugin. Neither are needed going forward.

**Comment by nolsherry** [comment]
@kbwood thanks for your response! :)
