### ISSUE TITLE
Inline SVG and Remote SVG load event listener differences

### ISSUE THREAD

**Issue by relector-tuxnix** [kbwood/svg#3]
Hi,

Loading an SVG graphic by specifying it as a string (inline) allows me to bind an event listener to an SVG element. The below code works:

``` javascript

 $('#world').svg(); 

var svg = $('#world').svg('get'); 

svg.load('<svg xmlns:svg="http://www.w3.org/2000/svg" xmlns="http://www.w3.org/2000/svg" xmlns:sodipodi="http://sodipodi.sourceforge.net/DTD/sodipodi-0.dtd" sodipodi:docname="New document 7"><rect id="rect1" x="100" y="20" width="150" height="100" fill="red" stroke="black" stroke-width="3"/></svg>', {addTo: true, onLoad: function() { console.log("done...");}}); 

$('#rect1', svg.root()).click(function(e) {
    console.log("Event works!");
});
```

However, when i attempt to load the SVG graphic from a file (remote), using the same SVG string only in a file, the event no longer works?

``` javascript

$('#world').svg(); 

var svg = $('#world').svg('get'); 

svg.load('drawing.svg', {addTo: true, onLoad: function() { console.log("done...");}}); 

$('#rect1', svg.root()).click(function(e) {
    console.log("Event works!");
});
```

I am using jquery v 1.7.2, jquery-svg v1.4.5, jquery-svg-dom v1.4.5 and Firefox v13.0.1.

Any help will be greatly appreciated.

Cheers.

**Comment by relector-tuxnix** [comment]
I ended up solving by using the "live" function in jquery:

``` javascript
$('#rect1', svg.root()).live('click', function(e) {
      console.log("Event works!");
});
```

The problem was that the SVG has not been loaded into the HTML DOM by the time the event was bound. So using the "live" function tells jquery retroactively to bind the event to the SVG element once it appears in the DOM.

**Comment by grekpg** [comment]
i use simple svg object and onlick not work 

div onClick="alert('clicked');" >
object rel="'.$i.'" class=" teamIdenOb" width="50" height="50" data="/ma'.$i.'.svg" type="image/svg+xml">
/object>/div> 

not work 

div onClick="alert('clicked');" >
aaa
/object>/div>
work

why ?
