### ISSUE TITLE
Incompatible with jQuery 1.8

### ISSUE THREAD

**Issue by peol** [kbwood/svg#5]
Hi,

this is what I've found is incompatible so far:
- https://github.com/kbwood/svg/blob/master/jquery.svgdom.js#L170 -- This csshook doesn't appear to work with e.g. `width` and `height`, it returns strings with units [e.g. `"192px"` instead of `192`] which isn't compatible with the jQuery API
- https://github.com/kbwood/svg/blob/master/jquery.svgdom.js#L237 -- This prefilter destroys compatibility after the Sizzle rewrite in 1.8. Various methods randomly breaks and continue to break after that
- `.siblings('.filter')` seems to be behaving oddly as well, and not filtering anymore, but that could easily be because of one of the other prefilters not working correctly, haven't found the exact issue yet

Here's a jsfiddle for the first two issues: http://jsfiddle.net/peol/fAbe8/ -- uncomment `delete $.expr.preFilter.CLASS;` to see how it fails internally in sizzle engine

**Comment by darky** [comment]
Confirm

**Comment by micha149** [comment]
Nothing changed yet?

**Comment by omolota** [comment]
Thanks a lot!
