### ISSUE TITLE
jQuery.browser is deprecated since 1.9

### ISSUE THREAD

**Issue by shuckster** [kbwood/svg#9]
http://jquery.com/upgrade-guide/1.9/#jquery-browser-removed

There are a few instances of this in your fine plugin.

It shouldn't take much effort to fix things. I'll try and do a pull-request myself when a) I have time, and b) I figure out how to do a pull-request, since I'm a Github newb. :p

**Comment by commonpike** [comment]
I took the code from here 
http://stackoverflow.com/questions/14379539/whats-a-quick-pure-javascript-replacement-for-jquery-browser-removed-in-jquer

and inserted that as a plugin before loading the svg plugins

**Comment by doedje** [comment]
That might work, but it's kinda dirty =]

I forked the project and try to get rid of the $.browser dependencies.... I removed one out of 4 already. I'll have to understand why the others are there first to fix them...

Help appreciated =]

You can find my repo here: https://github.com/doedje/jquery.svg

**Comment by williamdes** [comment]
cleanup day 😄
